/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AliasCertExtension"
 * 	found in "attestation.asn1"
 * 	`asn1c -D gen -no-gen-OER -no-gen-PER -no-gen-example`
 */

#ifndef	_DiceTcbInfo_H_
#define	_DiceTcbInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <NativeInteger.h>
#include "OperationalFlags.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FWIDLIST;

/* DiceTcbInfo */
typedef struct DiceTcbInfo {
	UTF8String_t	*vendor	/* OPTIONAL */;
	UTF8String_t	*model	/* OPTIONAL */;
	UTF8String_t	*version	/* OPTIONAL */;
	long	*svn	/* OPTIONAL */;
	long	*layer	/* OPTIONAL */;
	long	*index	/* OPTIONAL */;
	struct FWIDLIST	*fwids	/* OPTIONAL */;
	OperationalFlags_t	*flags	/* OPTIONAL */;
	OCTET_STRING_t	*vendorInfo	/* OPTIONAL */;
	OCTET_STRING_t	*type	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DiceTcbInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DiceTcbInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FWIDLIST.h"

#endif	/* _DiceTcbInfo_H_ */
#include <asn_internal.h>
