/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AliasCertExtension"
 * 	found in "attestation.asn1"
 * 	`asn1c -D gen -no-gen-OER -no-gen-PER -no-gen-example`
 */

#ifndef	_FWIDLIST_H_
#define	_FWIDLIST_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FWID;

/* FWIDLIST */
typedef struct FWIDLIST {
	A_SEQUENCE_OF(struct FWID) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FWIDLIST_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FWIDLIST;
extern asn_SET_OF_specifics_t asn_SPC_FWIDLIST_specs_1;
extern asn_TYPE_member_t asn_MBR_FWIDLIST_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FWID.h"

#endif	/* _FWIDLIST_H_ */
#include <asn_internal.h>
