/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AliasCertExtension"
 * 	found in "attestation.asn1"
 * 	`asn1c -D gen -no-gen-OER -no-gen-PER -no-gen-example`
 */

#ifndef	_OperationalFlags_H_
#define	_OperationalFlags_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OperationalFlags {
	OperationalFlags_notConfigured	= 0,
	OperationalFlags_notSecure	= 1,
	OperationalFlags_recovery	= 2,
	OperationalFlags_debug	= 3
} e_OperationalFlags;

/* OperationalFlags */
typedef BIT_STRING_t	 OperationalFlags_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OperationalFlags;
asn_struct_free_f OperationalFlags_free;
asn_struct_print_f OperationalFlags_print;
asn_constr_check_f OperationalFlags_constraint;
ber_type_decoder_f OperationalFlags_decode_ber;
der_type_encoder_f OperationalFlags_encode_der;
xer_type_decoder_f OperationalFlags_decode_xer;
xer_type_encoder_f OperationalFlags_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _OperationalFlags_H_ */
#include <asn_internal.h>
