/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AliasCertExtension"
 * 	found in "attestation.asn1"
 * 	`asn1c -D gen -no-gen-OER -no-gen-PER -no-gen-example`
 */

#ifndef	_FWID_H_
#define	_FWID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FWID */
typedef struct FWID {
	OBJECT_IDENTIFIER_t	 hashAlg;
	OCTET_STRING_t	 digest;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FWID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FWID;
extern asn_SEQUENCE_specifics_t asn_SPC_FWID_specs_1;
extern asn_TYPE_member_t asn_MBR_FWID_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _FWID_H_ */
#include <asn_internal.h>
