/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AliasCertExtension"
 * 	found in "attestation.asn1"
 * 	`asn1c -D gen -no-gen-OER -no-gen-PER -no-gen-example`
 */

#include "FWID.h"

asn_TYPE_member_t asn_MBR_FWID_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FWID, hashAlg),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashAlg"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FWID, digest),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"digest"
		},
};
static const ber_tlv_tag_t asn_DEF_FWID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FWID_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* digest */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* hashAlg */
};
asn_SEQUENCE_specifics_t asn_SPC_FWID_specs_1 = {
	sizeof(struct FWID),
	offsetof(struct FWID, _asn_ctx),
	asn_MAP_FWID_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_FWID = {
	"FWID",
	"FWID",
	&asn_OP_SEQUENCE,
	asn_DEF_FWID_tags_1,
	sizeof(asn_DEF_FWID_tags_1)
		/sizeof(asn_DEF_FWID_tags_1[0]), /* 1 */
	asn_DEF_FWID_tags_1,	/* Same as above */
	sizeof(asn_DEF_FWID_tags_1)
		/sizeof(asn_DEF_FWID_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_FWID_1,
	2,	/* Elements count */
	&asn_SPC_FWID_specs_1	/* Additional specs */
};

